/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Jun 23 19:54:53 2018. */

#include "smart-compass.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SmartCompassLocationMessage_fields[13] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , FIRST, SmartCompassLocationMessage, network_hash, network_hash, 0),
    PB_FIELD(  2, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, message_hash, network_hash, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, tx_peer_id, message_hash, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, tx_time, tx_peer_id, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, tx_ms, tx_time, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, peer_id, tx_ms, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, last_updated_at, peer_id, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, hue, last_updated_at, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, saturation, hue, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, latitude, saturation, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, longitude, latitude, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassLocationMessage, num_pins, longitude, 0),
    PB_LAST_FIELD
};

const pb_field_t SmartCompassPinMessage_fields[8] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , FIRST, SmartCompassPinMessage, network_hash, network_hash, 0),
    PB_FIELD(  2, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, SmartCompassPinMessage, message_hash, network_hash, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassPinMessage, tx_peer_id, message_hash, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassPinMessage, last_updated_at, tx_peer_id, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, SmartCompassPinMessage, latitude, last_updated_at, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, SmartCompassPinMessage, longitude, latitude, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, SmartCompassPinMessage, hue, longitude, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
